# Generated by Django 3.2.9 on 2021-12-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_auto_20211212_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='location',
        ),
    ]
