# Generated by Django 3.2.9 on 2021-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_remove_reservation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='time'),
        ),
    ]
