# Generated by Django 3.2.9 on 2021-12-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20211213_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='commerce.label'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='commerce.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commerce.label'),
        ),
    ]
