# Generated by Django 3.2.9 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_auto_20211213_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='Users/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
