# Generated by Django 3.2.9 on 2021-12-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_auto_20211213_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='commerce.user', verbose_name='users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.user', verbose_name='users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='users',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='commerce.user', verbose_name='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=0, max_length=255, verbose_name='user'),
            preserve_default=False,
        ),
    ]
