# Generated by Django 3.2.9 on 2021-12-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_auto_20211213_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
