# Generated by Django 3.2.9 on 2021-12-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='commerce.user', verbose_name='users'),
        ),
    ]
