# Generated by Django 3.2.9 on 2021-12-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_alter_opinion_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='commerce.user', verbose_name='users'),
        ),
    ]
