# Generated by Django 3.2.9 on 2021-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_alter_opinion_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='users',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='users'),
        ),
    ]
