# Generated by Django 3.2.9 on 2021-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_alter_opinion_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='users/', verbose_name='image'),
        ),
    ]
