# Generated by Django 3.2.9 on 2021-12-15 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0025_auto_20211213_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='users',
        ),
        migrations.AddField(
            model_name='opinion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='account.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
