# Generated by Django 3.2.9 on 2021-12-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20211215_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
