# Generated by Django 3.2.9 on 2021-12-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_remove_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='label',
        ),
    ]
