# Generated by Django 3.2.9 on 2021-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_auto_20211215_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
