# Generated by Django 3.2.9 on 2021-12-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_remove_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='label',
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commerce.label'),
        ),
    ]
