# Generated by Django 3.2.9 on 2021-12-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_auto_20211215_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commerce.center'),
        ),
    ]
