# Generated by Django 3.2.9 on 2021-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_auto_20211215_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='open_days',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='open_days'),
        ),
    ]
