# Generated by Django 3.2.9 on 2021-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0035_alter_center_open_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='center',
            name='close_days',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='close_days'),
        ),
        migrations.AddField(
            model_name='center',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='close_time'),
        ),
        migrations.AddField(
            model_name='center',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='open_time'),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='time'),
        ),
    ]
