# Generated by Django 3.2.9 on 2021-12-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0036_auto_20211215_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='time'),
        ),
    ]
