# Generated by Django 3.2.9 on 2021-12-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commerce.service'),
            preserve_default=False,
        ),
    ]
