# Generated by Django 3.2.9 on 2021-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0038_advertising_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='time',
        ),
    ]
