# Generated by Django 3.2.9 on 2021-12-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0039_remove_advertising_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='price',
        ),
        migrations.AddField(
            model_name='advertising',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commerce.center'),
            preserve_default=False,
        ),
    ]
