# Generated by Django 3.2.9 on 2021-12-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0040_auto_20211216_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='service',
        ),
        migrations.AlterField(
            model_name='advertising',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisings', to='commerce.center'),
        ),
    ]
