# Generated by Django 3.2.9 on 2021-12-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0042_remove_advertising_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisings', to='commerce.center'),
            preserve_default=False,
        ),
    ]
