# Generated by Django 3.2.9 on 2021-12-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0044_auto_20211216_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='center',
        ),
        migrations.AddField(
            model_name='center',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='commerce.service'),
        ),
    ]
