# Generated by Django 3.2.9 on 2021-12-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0049_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
