# Generated by Django 3.2.9 on 2021-12-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0053_auto_20211216_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='center',
        ),
        migrations.AddField(
            model_name='opinion',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='commerce.center'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='commerce.service'),
            preserve_default=False,
        ),
    ]
