# Generated by Django 3.2.9 on 2021-12-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0055_auto_20211216_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='service/', verbose_name='image')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_images', to='commerce.center')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Center_opinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Center_opinions', to='commerce.center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Center_opinions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='service/', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_opinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='copinion',
            name='center',
        ),
        migrations.RemoveField(
            model_name='copinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='simage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sopinion',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sopinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.AddField(
            model_name='service',
            name='background_image',
            field=models.ImageField(default=1, upload_to='service/', verbose_name='background_image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cimage',
        ),
        migrations.DeleteModel(
            name='Copinion',
        ),
        migrations.DeleteModel(
            name='Simage',
        ),
        migrations.DeleteModel(
            name='Sopinion',
        ),
        migrations.AddField(
            model_name='service_opinion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_opinions', to='commerce.service'),
        ),
        migrations.AddField(
            model_name='service_opinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_opinions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='service_image',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_image', to='commerce.service'),
        ),
    ]
