# Generated by Django 3.2.9 on 2021-12-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0056_auto_20211216_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_image',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_images', to='commerce.service'),
        ),
    ]
